# Generated by Django 4.0.5 on 2022-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avtor',
            field=models.ManyToManyField(to='main.author'),
        ),
    ]
