# Generated by Django 4.0.5 on 2022-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Fusce blandit nulla at massa venenatis, sed tincidunt nisltincidunt.', max_length=255),
        ),
    ]
