# Generated by Django 4.0.5 on 2022-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
