# Generated by Django 4.0.5 on 2022-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_expert_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='comment_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
